

#' Add explanatory (environmental) variables to 'site' dataframe.
#'
#' @param df Dataframe with context and 'cluster' columns.
#' @param clust_col Name of cluster column.
#' @param context Name of columns describing the context.
#' @param min_sites Minimum number of sites preferred in a cluster.
#' @param df_env Dataframe with 'site' and associated env values for floristic
#' 'sites'.
#' @param add_clust Any additional clusters (i.e. clusters not generated by
#' floristics such as land cover 'clusters')
#' @param add_env Dataframe with 'site' and associated env values for
#' additionalClusters 'sites'.
#' @param add_clust_col Character name of column in `add_clust` with 'clusters'.
#' @param set_min Filter clusters those with 'sites' >= minsites
#' @param env_cols Names of the columns containing the env variables.
#'
#' @return Dataframe of context columns, clustCol and envCols with rows from
#' both dfenv and addenv.
#'
#' @export
#'
#' @examples
  make_env_clust_df <- function(df
                                , clust_col = "cluster"
                                , context = "cell"
                                , min_sites = min_abs_sites
                                , df_env
                                , add_clust = NULL
                                , add_clust_col = "cluster"
                                , add_env
                                , env_cols
                                , set_min = FALSE
                                ) {

    df <- df %>%
      dplyr::select(any_of(context),!!ensym(clust_col)) %>%
      dplyr::inner_join(df_env %>%
                          na.omit()
                        )

    if(isTRUE(!is.null(add_clust))) {

      df_add <- add_clust %>%
        dplyr::select(any_of(context)
                      , !!ensym(clust_col) := !!ensym(add_clust_col)
                      ) %>%
        dplyr::inner_join(add_env %>%
                            na.omit()
                          )

      df <- df %>%
        dplyr::bind_rows(df_add)


    }

    df <- df %>%
      dplyr::mutate(!!ensym(clust_col) := factor(!!ensym(clust_col))) %>%
      dplyr::select(any_of(context),!!ensym(clust_col),all_of(env_cols))

    df <- if(set_min) df %>%
      dplyr::add_count(!!ensym(clust_col)) %>%
      dplyr::filter(n > min_sites) %>%
      dplyr::select(-n) else df

  }
