

#' Add explanatory (environmental) variables to 'site' dataframe.
#'
#' @param df Dataframe with 'site' and 'cluster' columns.
#' @param clustcol Name of cluster column.
#' @param sitecol Name of 'site' column.
#' @param minsites Minimum number of sites prefered in a cluster.
#' @param additionalClusters Any additional clusters (i.e. clusters not
#' generated by floristics such as land cover 'clusters')
#' @param dfenv Dataframe with 'site' and associated env values for floristic
#' 'sites'.
#' @param addenv Dataframe with 'site' and associated env values for
#' additionalClusters 'sites'.
#' @param setmin Filter clusters those with 'sites' >= minsites
#' @param envcols Names of the columns containing the env variables.
#'
#' @return Dataframe of siteCol, clustCol and envCols from both dfenv and addenv.
#' @export
#'
#' @examples
  make_env_clust_df <- function(df
                                , clustcol = "cluster"
                                , sitecol = "cell"
                                , minsites = minAbsSites
                                , additionalClusters
                                , dfenv
                                , addenv
                                , setmin = FALSE
                                , envcols = names(dfEnv)[-1]
                                ) {

    df <- if(setmin) df %>%
      dplyr::add_count(!!ensym(clustcol)) %>%
      dplyr::filter(n > minsites) %>%
      dplyr::select(-n) else df

    df %>%
      dplyr::select(!!ensym(sitecol),!!ensym(clustcol)) %>%
      dplyr::bind_rows(additionalClusters) %>%
      dplyr::select(!!ensym(sitecol),!!ensym(clustcol)) %>%
      dplyr::inner_join(dfenv %>%
                          dplyr::bind_rows(addenv) %>%
                          na.omit()
                        ) %>%
      dplyr::mutate(!!ensym(clustcol) := factor(!!ensym(clustcol))) %>%
      na.omit()

  }
