

#' Add explanatory (environmental) variables to 'site' dataframe.
#'
#' @param df Dataframe with context and 'cluster' columns.
#' @param clust_col Name of cluster column.
#' @param context Name of columns describing the context.
#' @param min_sites Minimum number of sites preferred in a cluster.
#' @param df_env Dataframe with 'site' and associated env values for floristic
#' 'sites'.
#' @param add_clust Any additional clusters (i.e. clusters not generated by
#' floristics such as land cover 'clusters')
#' @param add_env Dataframe with 'site' and associated env values for
#' additionalClusters 'sites'.
#' @param set_min Filter clusters those with 'sites' >= minsites
#' @param env_cols Names of the columns containing the env variables.
#'
#' @return Dataframe of context columns, clustCol and envCols with rows from
#' both dfenv and addenv.
#'
#' @export
#'
#' @examples
  make_env_clust_df <- function(df
                                , clust_col = "cluster"
                                , context = "cell"
                                , min_sites = min_abs_sites
                                , df_env
                                , add_clust
                                , add_env
                                , env_cols
                                , set_min = FALSE
                                ) {

    df <- df %>%
      dplyr::bind_rows(add_clust) %>%
      dplyr::select(all_of(context),!!ensym(clust_col)) %>%
      dplyr::inner_join(df_env %>%
                          dplyr::bind_rows(add_env) %>%
                          na.omit()
                        ) %>%
      dplyr::mutate(!!ensym(clust_col) := factor(!!ensym(clust_col))) %>%
      dplyr::select(all_of(context),!!ensym(clust_col),all_of(env_cols)) %>%
      na.omit()

    df <- if(set_min) df %>%
      dplyr::add_count(!!ensym(clust_col)) %>%
      dplyr::filter(n > min_sites) %>%
      dplyr::select(-n) else df

  }
